<a href="https://colab.research.google.com/github/rupali-01/gradientdescent/blob/main/gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
from google.colab import files
uploaded = files.upload()

Saving insurance_data (1).csv to insurance_data (1).csv


In [3]:
df = pd.read_csv(list(uploaded.keys())[0])

In [4]:
df

age  affordibility  bought_insurance
0    22              1                 0
1    25              0                 0
2    47              1                 1
3    52              0                 0
4    46              1                 1
5    56              1                 1
6    55              0                 0
7    60              0                 1
8    62              1                 1
9    61              1                 1
10   18              1                 0
11   28              1                 0
12   27              0                 0
13   29              0                 0
14   49              1                 1
15   55              1                 1
16   25              0                 1
17   58              1                 1
18   19              0                 0
19   18              1                 0
20   21              1                 0
21   26              0                 0
22   40              1                 1
23   45              1                 1
24   50              1                 1
25   54              1                 1
26   23              1                 0
27   46              1                 0

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,train_size=0.8)

In [7]:
X_train

age  affordibility
26   23              1
9    61              1
4    46              1
22   40              1
5    56              1
27   46              1
10   18              1
7    60              0
12   27              0
11   28              1
24   50              1
18   19              0
1    25              0
0    22              1
21   26              0
20   21              1
17   58              1
2    47              1
3    52              0
23   45              1
6    55              0
15   55              1

In [8]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [9]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=500)

Epoch 1/500


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 933ms/step - accuracy: 0.4545 - loss: 0.7544
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.4545 - loss: 0.7539
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.4545 - loss: 0.7534
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.4545 - loss: 0.7529
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.4545 - loss: 0.7524
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.4545 - loss: 0.7520
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.4545 - loss: 0.7515
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.4545 - loss: 0.7510
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.4545 - loss: 0.7505
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.4545 - loss: 0.7500
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.4545 - loss: 0.7496
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.4545 - loss: 0.7491


In [10]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step - accuracy: 0.6667 - loss: 0.5980


[0.5979940295219421, 0.6666666865348816]

In [11]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step


array([[0.65140706],
       [0.5918772 ],
       [0.44112504],
       [0.6640873 ],
       [0.6433701 ],
       [0.4480801 ]], dtype=float32)

In [12]:
coef, intercept = model.get_weights()

In [13]:
coef, intercept

(array([[0.7041618],
        [0.6576201]], dtype=float32),
 array([-0.41263783], dtype=float32))

FUNCTION DEFINED:

In [14]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
%matplotlib inline

In [15]:
def upload_file():
  from google.colab import files
  uploaded = files.upload()
  df = pd.read_csv(list(uploaded.keys())[0])
  print("Uploaded dataset columns:", df.columns)
  return df

In [28]:
def preprocess_data(df):
    x = df[['age', 'affordibility']]
    y = df['bought_insurance']
    x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8)
    x_train_scaled = x_train.copy()
    x_test_scaled = x_test.copy()
    x_train_scaled['age'] = x_train_scaled['age'] / 100
    x_test_scaled['age'] = x_test_scaled['age'] / 100
    return x_train_scaled, x_test_scaled, y_train, y_test


In [29]:
def create_model():
    model = keras.Sequential([
        keras.layers.Dense(1, input_shape=(2,), activation='sigmoid',
                           kernel_initializer='ones', bias_initializer='zeros')
    ])
    model.compile(optimizer='adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])
    return model


In [30]:
def train_model(model, x_train, y_train):
    model.fit(x_train, y_train, epochs=500)
    return model


In [31]:
def evaluate_model(model, x_test, y_test):
    loss, accuracy = model.evaluate(x_test, y_test)
    return loss, accuracy


In [32]:
def get_model_weights(model):
    coef, intercepts = model.get_weights()
    return coef, intercepts


In [33]:
def main():
    df = upload_file()
    print(df.head())

    x_train_scaled, x_test_scaled, y_train, y_test = preprocess_data(df)

    model = create_model()
    model = train_model(model, x_train_scaled, y_train)

    loss, accuracy = evaluate_model(model, x_test_scaled, y_test)
    print(f"Test Loss: {loss}, Test Accuracy: {accuracy}")

    prediction = model.predict(x_train_scaled)
    coef, intercepts = get_model_weights(model)
    print(f"Model Coefficients: {coef}, Intercepts: {intercepts}")

    return model, prediction


In [38]:
if __name__ == "__main__":
 main()

Saving insurance_data (1).csv to insurance_data (1) (4).csv
Uploaded dataset columns: Index(['age', 'affordibility', 'bought_insurance'], dtype='object')
   age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1
Epoch 1/500


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 839ms/step - accuracy: 0.5000 - loss: 0.7338
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.7334
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7330
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7326
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7321
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7317
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7313
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7309
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7305
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7301
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7297
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7293
